const quotes = [
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { text: "Get busy living or get busy dying.", author: "Stephen King" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { text: "To be the best, you must be able to handle the worst.", author: "Wilson Kanadi" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "Life is short, and it's up to you to make it sweet.", author: "Sarah Louise Delany" },
    { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "You do not find the happy life. You make it.", author: "Camilla E. Kimball" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin" },
    { text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is going from failure to failure without losing your enthusiasm.", author: "Winston Churchill" },
    { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { text: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "You do not find the happy life. You make it.", author: "Camilla E. Kimball" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { text: "Get busy living or get busy dying.", author: "Stephen King" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { text: "To be the best, you must be able to handle the worst.", author: "Wilson Kanadi" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "Life is short, and it's up to you to make it sweet.", author: "Sarah Louise Delany" },
    { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "You do not find the happy life. You make it.", author: "Camilla E. Kimball" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin" },
    { text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is going from failure to failure without losing your enthusiasm.", author: "Winston Churchill" },
    { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { text: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "You do not find the happy life. You make it.", author: "Camilla E. Kimball" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Life is short, and it's up to you to make it sweet.", author: "Sarah Louise Delany" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "You do not find the happy life. You make it.", author: "Camilla E. Kimball" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin" },
    { text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is going from failure to failure without losing your enthusiasm.", author: "Winston Churchill" },
    { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { text: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "You do not find the happy life. You make it.", author: "Camilla E. Kimball" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Life is short, and it's up to you to make it sweet.", author: "Sarah Louise Delany" },
    { text: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "You do not find the happy life. You make it.", author: "Camilla E. Kimball" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "We don't see things as they are, we see them as we are.", author: "Anaïs Nin" },
    { text: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Success is going from failure to failure without losing your enthusiasm.", author: "Winston Churchill" },
    { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { text: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James" },
    { text: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "The best way to predict your future is to create it.", author: "Peter Drucker" },
    { text: "You only fail when you stop trying.", author: "Albert Einstein" },
    { text: "Your limitation—it's only your imagination.", author: "Unknown" },
    { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { text: "Great things never come from comfort zones.", author: "Unknown" },
    { text: "Dream it. Wish it. Do it.", author: "Unknown" },
    { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
    { text: "Dream bigger. Do bigger.", author: "Unknown" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
    { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    { text: "Do what you love, love what you do.", author: "Unknown" },
    { text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
    { text: "Dream it. Believe it. Build it.", author: "Unknown" },
    { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
    { text: "Hard work beats talent when talent doesn’t work hard.", author: "Kevin Durant" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { text: "Great things never come from comfort zones.", author: "Unknown" },
    { text: "Dream it. Wish it. Do it.", author: "Unknown" },
    { text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
    { text: "Dream bigger. Do bigger.", author: "Unknown" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
    { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    { text: "Do what you love, love what you do.", author: "Unknown" },
    { text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
    { text: "Dream it. Believe it. Build it.", author: "Unknown" },
    { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
    { text: "Hard work beats talent when talent doesn’t work hard.", author: "Kevin Durant" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You only fail when you stop trying.", author: "Albert Einstein" },
    { text: "Your limitation—it's only your imagination.", author: "Unknown" },
    { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { text: "Great things never come from comfort zones.", author: "Unknown" },
    { text: "Dream it. Wish it. Do it.", author: "Unknown" },
    { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
    { text: "Dream bigger. Do bigger.", author: "Unknown" },
    { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
    { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    { text: "Do what you love, love what you do.", author: "Unknown" },
    { text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown" },
    { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
    { text: "Dream it. Believe it. Build it.", author: "Unknown" },
    { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
    { text: "Hard work beats talent when talent doesn’t work hard.", author: "Kevin Durant" },
    { text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "The act of dying is one of the acts of life.", author: "Marcus Aurelius" },
    { text: "Justice is the constant and perpetual will to allot to every man his due.", author: "Ulpian" },
    { text: "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion.", author: "Albert Camus" },
    { text: "A person is a fool to become a detective and then complain about the dirt and grime of the profession.", author: "Unknown" },
    { text: "Murder is always a mistake. One should never do anything that one cannot talk about after dinner.", author: "Oscar Wilde" },
    { text: "The only crime is a crime against the self.", author: "Unknown" },
    { text: "It is better to risk saving a guilty person than to condemn an innocent one.", author: "Voltaire" },
    { text: "Those who make peaceful revolution impossible will make violent revolution inevitable.", author: "John F. Kennedy" },
    { text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
    { text: "Crime is a social construct created by those in power to control those who are not.", author: "Unknown" },
    { text: "Injustice anywhere is a threat to justice everywhere.", author: "Martin Luther King Jr." },
    { text: "The more corrupt the state, the more numerous the laws.", author: "Tacitus" },
    { text: "To be a good person, you must be a good judge of character.", author: "Unknown" },
    { text: "Justice delayed is justice denied.", author: "William E. Gladstone" },
    { text: "Every man is guilty of all the good he did not do.", author: "Voltaire" },
    { text: "Evil is not a thing but a process, a process of becoming.", author: "Unknown" },
    { text: "Violence is the last refuge of the incompetent.", author: "Isaac Asimov" },
    { text: "When the law is an ass, it is best to avoid it.", author: "Unknown" },
    { text: "The only thing necessary for the triumph of evil is for good men to do nothing.", author: "Edmund Burke" },
    { text: "Crime does not pay, but they don't always catch the criminals.", author: "Unknown" },
    { text: "An eye for an eye makes the whole world blind.", author: "Mahatma Gandhi" },
    { text: "The darkest places in hell are reserved for those who maintain their neutrality in times of moral crisis.", author: "Dante Alighieri" },
    { text: "The truth will set you free, but first it will make you miserable.", author: "James A. Garfield" },
    { text: "A society that has more justice is a society that needs less charity.", author: "Ralph Nader" },
    { text: "Justice is not a state of being, it is an act.", author: "Unknown" },
    { text: "The measure of a society is how it treats its most vulnerable members.", author: "Mahatma Gandhi" },
    { text: "A lie can travel halfway around the world while the truth is putting on its shoes.", author: "Jonathan Swift" },
    { text: "The law is reason, free from passion.", author: "Aristotle" },
    { text: "The only good is knowledge and the only evil is ignorance.", author: "Socrates" },
    { text: "There is no greater tyranny than that which is perpetrated under the shield of the law and in the name of justice.", author: "Charles de Montesquieu" },
    { text: "The law must be stable, but it must not stand still.", author: "Roscoe Pound" },
    { text: "To punish the oppressors of humanity is the most gratifying of all emotions.", author: "Unknown" },
    { text: "The only true crime is not to have been born in a free society.", author: "Unknown" },
    { text: "Justice is truth in action.", author: "Benjamin Disraeli" },
    { text: "He who commits injustice is ever made more wretched than he who suffers it.", author: "Plato" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { text: "Justice is the sum of all virtues.", author: "Unknown" },
    { text: "Injustice is a serious crime, and it is often met with swift retribution.", author: "Unknown" },
    { text: "The measure of a country's greatness is its ability to retain compassion in times of crisis.", author: "Unknown" },
    { text: "No one is above the law and no one is below its protection.", author: "Unknown" },
    { text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
    { text: "Justice is not about punishing the guilty; it is about protecting the innocent.", author: "Unknown" },
    { text: "Crime is the result of a failure to adapt to societal norms.", author: "Unknown" },
    { text: "A society that is afraid of its own reflection will never see its own potential.", author: "Unknown" },
    { text: "The only thing worse than being a victim of a crime is being a perpetrator.", author: "Unknown" },
    { text: "To be innocent is not to be untroubled, but to be untroubled is to be innocent.", author: "Unknown" },
    { text: "Violence is a disease that corrupts the soul of society.", author: "Unknown" },
    { text: "Justice is not a privilege, it is a right.", author: "Unknown" },
    { text: "The fear of crime is often greater than the reality of crime.", author: "Unknown" },
    { text: "To be truly just is to be truly free.", author: "Unknown" },
    { text: "The more laws there are, the more criminals there will be.", author: "Unknown" },
    { text: "Evil unchecked grows, and the more evil becomes, the more it needs to be checked.", author: "Unknown" },
    { text: "An unjust law is no law at all.", author: "Saint Augustine" },
    { text: "Crime is only a symptom of a deeper disease within society.", author: "Unknown" },
    { text: "Justice is not about revenge; it is about accountability.", author: "Unknown" },
    { text: "The law is a living thing that reflects the values of a society.", author: "Unknown" },
    { text: "The greatest crime is to be untrue to oneself.", author: "Unknown" },
    { text: "Violence begets violence, and the cycle continues.", author: "Unknown" },
    { text: "Justice is not a commodity to be bought or sold.", author: "Unknown" },
    { text: "The law should serve humanity, not the other way around.", author: "Unknown" },
    { text: "Crime is a consequence of neglect, not of nature.", author: "Unknown" },
    { text: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin" },
    { text: "To protect the innocent is the highest form of justice.", author: "Unknown" },
    { text: "A crime is a crime, whether it is committed in the name of good or evil.", author: "Unknown" },
    { text: "Justice is the equilibrium between rights and responsibilities.", author: "Unknown" },
    { text: "The law is a guide for moral behavior, not a shield for the immoral.", author: "Unknown" },
    { text: "The pursuit of justice is the most noble of causes.", author: "Unknown" },
    { text: "The crime of the future will be against the spirit, not the body.", author: "Unknown" },
    { text: "Justice is a virtue that transcends the law.", author: "Unknown" },
    { text: "A society that punishes its criminals without reforming them is doomed to repeat its mistakes.", author: "Unknown" },
    { text: "The essence of justice is fairness, not vengeance.", author: "Unknown" },
    { text: "The law is not just about rules; it is about protecting human dignity.", author: "Unknown" },
    { text: "A society's true strength is measured by its ability to uphold justice.", author: "Unknown" },
    { text: "Violence is a sign of weakness, not strength.", author: "Unknown" },
    { text: "Justice requires more than the letter of the law; it requires the spirit of fairness.", author: "Unknown" },
    { text: "A crime committed in anger is often a crime committed in ignorance.", author: "Unknown" },
    { text: "The law is an instrument of justice, not a weapon of oppression.", author: "Unknown" },
    { text: "To be just is to be compassionate.", author: "Unknown" },
    { text: "A society that ignores its criminals is a society that breeds more crime.", author: "Unknown" },
    { text: "The pursuit of justice is the highest form of respect for human dignity.", author: "Unknown" },
    { text: "Justice is the balance between liberty and security.", author: "Unknown" },
    { text: "The law should be a reflection of humanity's highest ideals.", author: "Unknown" },
    { text: "A crime is a breach of social trust, not just a violation of the law.", author: "Unknown" },
    { text: "To administer justice is to respect the humanity of every individual.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "The law should be an expression of our highest values, not our lowest fears.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "Crime is a failure of society, not just of the individual.", author: "Unknown" },
    { text: "To be just is to be committed to the truth.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "To ignore the law is to ignore the fabric of society.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The measure of a just society is how it treats its most vulnerable members.", author: "Unknown" },
    { text: "The law is a promise to uphold the values of justice.", author: "Unknown" },
    { text: "Justice requires not only the application of the law but also the spirit of fairness.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "A society that is just is a society that is free.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "A society that does not seek justice for all is a society that does not deserve peace.", author: "Unknown" },
    { text: "The pursuit of justice is the pursuit of truth.", author: "Unknown" },
    { text: "Crime is a betrayal of the social contract.", author: "Unknown" },
    { text: "To be just is to seek balance in all things.", author: "Unknown" },
    { text: "The law is a mirror of the society it serves.", author: "Unknown" },
    { text: "Justice is the foundation of a healthy society.", author: "Unknown" },
    { text: "The law should be an instrument for the greater good.", author: "Unknown" },
    { text: "A society that does not enforce justice is a society that is doomed to chaos.", author: "Unknown" },
    { text: "The true measure of justice is not in the law but in its application.", author: "Unknown" },
    { text: "To be just is to be committed to the truth, no matter the cost.", author: "Unknown" },
    { text: "Justice is a principle that transcends time and place.", author: "Unknown" },
    { text: "The law should reflect our highest values, not our lowest fears.", author: "Unknown" },
    { text: "A society that does not value justice is a society that is lost.", author: "Unknown" },
    { text: "The law is a reflection of the values of society.", author: "Unknown" },
    { text: "Justice is the harmony between liberty and security.", author: "Unknown" },
    { text: "The greatest crime is to be indifferent to the suffering of others.", author: "Unknown" },
    { text: "A just society is one that values every individual's right to fairness.", author: "Unknown" },
    { text: "Justice is not a privilege but a right of every human being.", author: "Unknown" },
    { text: "To administer justice is to honor the human spirit.", author: "Unknown" },
    { text: "The law should protect the innocent and punish the guilty.", author: "Unknown" },
    { text: "Justice is the antidote to the poison of crime.", author: "Unknown" },
    { text: "The real crime is the failure to seek justice.", author: "Unknown" },
    { text: "Programming is not about what you know; it's about what you can figure out.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Code is like humor. When you have to explain it, it’s bad.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best error message is the one that comes with a solution.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Simplicity is the soul of efficiency.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Good code is its own best documentation.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { text: "Programming isn't about what you know; it's about what you can figure out.", author: "Chris Pine" },
    { text: "Code never lies, comments sometimes do.", author: "Ron Jeffries" },
    { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
    { text: "In programming, the hard part isn't solving problems, but deciding what problems to solve.", author: "Paul Graham" },
    { text: "The most disastrous thing that you can ever learn is your first programming language.", author: "Alan Kay" },
    { text: "It's not a bug – it's an undocumented feature.", author: "Anonymous" },
    { text: "Programming is like kicking yourself in the face, sooner or later your nose will bleed.", author: "Anonymous" },
    { text: "The only way to learn a new programming language is by writing programs in it.", author: "Dennis Ritchie" },
    { text: "Good programmers use their brains, but good programmers know how to use their brains.", author: "Robert C. Martin" },
    { text: "Code is like a poem: the right line can bring the whole piece to life.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is the art of algorithm design and the craft of debugging errant code.", author: "Elliot Alderson" },
    { text: "The best code is no code at all.", author: "Jeff Atwood" },
    { text: "Programming is not about typing, it’s about thinking.", author: "Rich Hickey" },
    { text: "A good programmer is someone who always looks both ways before crossing a one-way street.", author: "Anonymous" },
    { text: "The key to performance is elegance, not battles with the operating system.", author: "James Gosling" },
    { text: "Programming is the closest thing we have to a superpower.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "If you don’t like something, change it. If you can’t change it, change your attitude.", author: "Maya Angelou" },
    { text: "In programming, we have to learn how to create solutions, not just find them.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "There are only two hard things in computer science: cache invalidation and naming things.", author: "Phil Karlton" },
    { text: "The best way to learn programming is to get your hands dirty.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Code that’s easy to understand is easy to change.", author: "Robert C. Martin" },
    { text: "To understand recursion, you must first understand recursion.", author: "Anonymous" },
    { text: "The purpose of software engineering is to control complexity, not to create it.", author: "Pamela Zave" },
    { text: "Good code is its own best documentation.", author: "Steve McConnell" },
    { text: "To err is human; to debug, divine.", author: "Anonymous" },
    { text: "Programming is the science of building algorithms.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A program that produces incorrect results twice is a bug; once is an experiment.", author: "Anonymous" },
    { text: "Programming is not about knowing everything; it's about knowing where to find the answers.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Writing code is easy; writing good code is hard.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The goal of programming is to make complex things simple.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is the one you didn’t have to write.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The beauty of code is in its simplicity.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is not just about writing code; it's about solving problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The purpose of a computer science education is not to learn to program but to learn to think.", author: "John McCarthy" },
    { text: "In programming, you always need to be curious and keep learning.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are always learning and evolving.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Every programming language is just a different way to express the same concepts.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Debugging is twice as hard as writing the code in the first place.", author: "Brian W. Kernighan" },
    { text: "Code is poetry.", author: "Matt Mullenweg" },
    { text: "In programming, you don’t get things right the first time; you get them right after many attempts.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to approach coding problems is to break them into smaller, manageable pieces.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A good programmer is someone who always looks both ways before crossing a one-way street.", author: "Anonymous" },
    { text: "The key to successful programming is not just writing code but also understanding the problem you are solving.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "To be a good programmer, you need to be a good problem solver.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The most efficient code is the code you don’t need to write.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The power of a programming language is not in its syntax but in its ability to solve problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A programming language is a set of rules for solving problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The secret to mastering programming is persistence and practice.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a journey, not a destination.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A good programmer is someone who can adapt to any programming language and solve problems efficiently.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is not about writing code; it’s about creating solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true essence of programming is to find elegant solutions to complex problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "To be a successful programmer, you need to be both creative and analytical.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In coding, there are no shortcuts; only hard work and dedication lead to success.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is the one that is simple, clean, and easy to understand.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is the art of breaking down complex problems into simpler ones.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A programmer’s job is to find the most efficient way to solve a problem.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The beauty of programming lies in the elegance of the solution.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Every line of code should have a purpose and contribute to the overall solution.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In programming, the journey is as important as the destination.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is an art, and like all arts, it requires practice and patience.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who keep learning and improving their skills.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is like a puzzle; the satisfaction comes from finding the right pieces.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A programmer’s most important skill is the ability to think logically and solve problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Good programming practices lead to better code and more efficient solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is about making the impossible possible through the power of logic and creativity.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to become a better programmer is to write more code and learn from your mistakes.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In coding, there is always room for improvement and optimization.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The greatest challenge in programming is not solving the problem, but understanding it.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who never stop learning and growing.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a craft that requires constant refinement and dedication.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The art of programming is in finding elegant solutions to complex problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a blend of logic, creativity, and perseverance.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A good programmer is someone who can solve problems efficiently and elegantly.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The joy of programming comes from solving problems and creating something new.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "To be a successful coder, you need to be passionate about learning and problem-solving.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to approach coding challenges is with a curious and open mind.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is an endless journey of learning and discovery.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The beauty of programming is in the simplicity of the solution and the elegance of the code.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In programming, there is no one-size-fits-all solution; every problem requires a unique approach.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a powerful tool for creating and solving complex problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is the one that is easy to read, understand, and maintain.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A programmer’s success is measured by the quality and efficiency of their code.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In coding, every challenge is an opportunity to learn and grow.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is about finding creative solutions to difficult problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The most satisfying part of programming is seeing your code come to life and solve real-world problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who are always curious and eager to learn new things.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is both an art and a science, requiring a blend of logic and creativity.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a discipline that rewards patience, practice, and persistence.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "To be a great programmer, you need to be passionate about problem-solving and continuous learning.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The joy of coding comes from the satisfaction of solving complex problems and creating something useful.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In programming, there is always a better way to solve a problem; it's up to you to find it.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to improve your coding skills is to keep challenging yourself with new problems and projects.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a journey of continuous improvement and learning.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who are passionate about their craft and committed to excellence.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is an iterative process of trial and error, learning, and growth.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true measure of a programmer’s skill is their ability to solve problems efficiently and effectively.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is not just a job; it's a way of thinking and solving problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A successful coder is one who can adapt to new challenges and continuously improve their skills.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The art of programming is in creating elegant solutions that are both efficient and effective.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a skill that combines logic, creativity, and perseverance.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is the one that solves the problem with the least amount of complexity.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In coding, simplicity is often the key to a successful solution.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is about making the complex simple and solving problems with clarity.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true beauty of code lies in its ability to solve problems and create value.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A good programmer is someone who can write code that is both efficient and easy to understand.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The most rewarding part of programming is seeing your code come to life and make a difference.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "To be an effective programmer, you need to be both analytical and creative.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is an art that requires practice, patience, and passion.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to improve your programming skills is to keep coding and learning from your experiences.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a journey of constant learning and adaptation.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The most successful programmers are those who are committed to continuous improvement.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is about solving problems with creativity and logic.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A programmer’s success is determined by their ability to solve problems and deliver value.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is the one that is simple, elegant, and effective.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is not just a skill; it's a mindset and a way of thinking.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The joy of coding comes from the satisfaction of solving complex problems and creating useful solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A great programmer is one who can adapt to new challenges and continuously improve their skills.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a continuous journey of learning, problem-solving, and innovation.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who approach coding with curiosity and a desire to learn.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is the art of creating solutions that are both efficient and elegant.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A successful coder is one who can solve problems effectively and continuously improve their skills.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In coding, every problem is an opportunity to learn and grow.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a blend of logic, creativity, and persistence.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true measure of a programmer’s skill is their ability to create efficient and elegant solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a craft that requires constant refinement and dedication.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The most satisfying part of programming is seeing your code solve real-world problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A good programmer is one who can approach problems with a clear and logical mindset.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to improve your coding skills is to keep challenging yourself and learning from your experiences.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a journey of discovery, learning, and growth.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who continuously strive for improvement and excellence.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a process of constant learning and adaptation to new challenges.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The joy of programming comes from solving problems and creating innovative solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A great programmer is one who can solve problems with creativity, logic, and efficiency.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is not just about writing code; it's about solving problems and creating value.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is the one that balances efficiency, readability, and functionality.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a craft that requires a blend of logic, creativity, and persistence.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A successful coder is one who continuously learns, adapts, and improves their skills.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is about solving problems with creativity, logic, and efficiency.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true art of coding lies in creating elegant solutions that are both efficient and effective.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a journey of constant learning and discovery, with each problem offering a new opportunity to grow.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who are passionate about learning, problem-solving, and continuous improvement.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a skill that combines logic, creativity, and perseverance to create innovative solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The most rewarding part of coding is seeing your ideas come to life and solve real-world problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A good programmer is someone who can approach problems with a clear and logical mindset while being open to new ideas.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to enhance your coding skills is to keep experimenting, learning, and challenging yourself.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a continuous journey of learning and growth, with each challenge offering a new opportunity to improve.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true measure of a programmer’s skill is their ability to create solutions that are both elegant and efficient.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In programming, every challenge is an opportunity to learn, innovate, and grow.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is the one that is simple, effective, and solves the problem at hand.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is about creating solutions that are both functional and elegant, combining logic and creativity.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A successful coder is one who continuously learns, adapts, and strives for excellence.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a journey of discovery, with each problem presenting a new challenge and opportunity for growth.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The joy of programming comes from the satisfaction of solving problems and creating innovative solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A great programmer is someone who can blend logic, creativity, and perseverance to create effective solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is an art form that requires constant practice, refinement, and dedication.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best programmers are those who continuously seek to improve their skills and solve problems creatively.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a process of constant learning, adaptation, and innovation.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true beauty of programming lies in its ability to solve complex problems and create meaningful solutions.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A successful coder is one who approaches challenges with a clear, logical mindset and a willingness to learn.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is one that balances simplicity, efficiency, and effectiveness.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is a craft that requires a balance of logic, creativity, and dedication.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The most rewarding part of programming is seeing your ideas come to life and solve real-world problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A good programmer is one who can approach problems with a clear and logical mindset while continuously learning and improving.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best way to improve your programming skills is to keep experimenting with new ideas and challenging yourself.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is an ongoing journey of discovery and growth, with each challenge offering a new opportunity to learn.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The true measure of a programmer’s skill is their ability to create efficient, elegant solutions to complex problems.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "In programming, every problem is a chance to innovate and improve your skills.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "The best code is one that is both effective and simple, solving the problem with clarity and precision.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Programming is about crafting solutions that are both functional and elegant, requiring a blend of logic and creativity.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "A successful coder continuously learns, adapts, and strives for excellence in their craft.", author: "Kanishk Raj / ProgrammerKR" },
    { text: "Coding is a continuous journey of problem-solving and discovery, with each challenge offering a new opportunity to grow.", author: "Kanishk Raj / ProgrammerKR" }
];


document.getElementById('generate-btn').addEventListener('click', () => {
    const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    document.getElementById('quote').textContent = `"${randomQuote.text}"`;
    document.getElementById('author').textContent = `- ${randomQuote.author}`;
});
